#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.2.4f1_cb262d9ddeaf"
#define UNITY_VERSION_FULL_NICE "2018.2.4f1 (cb262d9ddeaf)"
#define UNITY_VERSION_BLD 13313581
#define UNITY_VERSION_DATE 1534111278
#define UNITY_VERSION_WIN "2018.2.4.13313581"
#define UNITY_VERSION_BRANCH "2018.2/release"
